name = "hung/tes01"
version = "0.0.0"
compiler = "v1.1.11"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'hung/tes01'"

[repository]
user = "hung"
project = "tes01"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
